/* Loading */

export const LOADINGETHERIUMADRESS_REQUEST = 'LOADINGETHERIUMADRESS_REQUEST'
export const LOADINGETHERIUMADRESS_SUCCESS = 'LOADINGETHERIUMADRESS_SUCCESS'
export const LOADINGETHERIUMADRESS__FAILURE = 'LOADINGETHERIUMADRESS__FAILURE'